2022-02-01 00:00:15,828 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:00:47,916 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:01:20,003 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:01:52,127 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:02:24,213 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:02:56,355 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:03:28,498 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 00:04:00,899 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:52:05,877 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:52:08,206 WARN [hikariCP housekeeper] c.z.h.p.HikariPool [HikariPool.java:766] hikariCP - Thread starvation or clock leap detected (housekeeper delta=15h48m8s567ms780Âµs800ns).
2022-02-01 15:52:38,921 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:53:11,873 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:53:44,230 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:54:16,821 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:54:36,776 WARN [lettuce-nioEventLoop-4-2] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@74d82a3b.
2022-02-01 15:54:49,122 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:55:09,827 WARN [lettuce-nioEventLoop-4-3] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@3e9e0ef4.
2022-02-01 15:55:21,379 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:55:42,157 WARN [lettuce-nioEventLoop-4-4] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@59fec595.
2022-02-01 15:55:53,583 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:56:26,022 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:56:58,249 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:57:30,773 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:58:03,091 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:58:35,354 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:59:07,676 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 15:59:40,077 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:00:12,329 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:00:44,622 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:01:16,923 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:01:49,221 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:02:21,654 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:02:53,865 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:03:26,057 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:03:58,383 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:04:30,724 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:05:02,958 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:05:35,352 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:06:07,489 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:06:39,787 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:07:12,253 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:07:44,477 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:08:16,729 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:08:49,032 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:09:21,358 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:09:53,789 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:10:26,031 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:10:58,374 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:11:30,622 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:12:02,856 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:12:35,082 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:13:07,321 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:13:39,624 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:14:11,891 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:14:44,257 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:15:16,700 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:15:49,149 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:16:21,479 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:16:53,680 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:17:25,830 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:17:58,121 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:18:30,773 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:19:03,027 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:19:35,374 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:20:07,625 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:20:39,827 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:21:12,351 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:21:44,688 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:22:17,088 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:22:49,330 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:23:21,654 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:23:53,829 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:24:26,224 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:24:58,581 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:25:30,754 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:26:02,956 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:26:35,285 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:27:07,627 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:27:40,075 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:28:12,225 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:28:44,432 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:29:16,723 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:29:49,091 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:30:21,354 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:30:53,582 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:31:25,723 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:31:58,081 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:32:30,387 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:33:02,722 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:33:34,830 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:34:07,082 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:34:39,486 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:35:11,831 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:35:44,189 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:36:16,684 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:36:49,149 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:37:21,357 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:37:53,652 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:38:26,090 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:38:58,490 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:39:30,823 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:40:02,929 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:40:35,128 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:41:07,483 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:41:39,692 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:42:11,953 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:42:44,356 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:43:16,529 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:43:48,781 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:44:21,284 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:44:53,684 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:45:26,055 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:45:58,329 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:46:30,656 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:47:02,953 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:47:35,155 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:48:07,483 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:48:39,630 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:49:11,890 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:49:44,176 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:50:16,597 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:50:48,891 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:51:21,283 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:51:53,676 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:52:25,973 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:52:58,253 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:53:30,722 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:54:03,127 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:54:35,325 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:55:07,574 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:55:39,692 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:56:12,185 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:56:44,686 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:57:16,858 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:57:49,189 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:58:21,451 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:58:53,692 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:59:26,091 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 16:59:58,429 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:00:30,651 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:01:02,980 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:01:35,158 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:02:07,351 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:02:39,553 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:03:11,779 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:03:43,953 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:04:16,128 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:04:48,330 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:05:20,556 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:05:52,754 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:06:25,091 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:06:57,230 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:07:29,551 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:08:01,791 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:08:34,159 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:09:06,383 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:09:38,822 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:10:11,176 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:10:43,485 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:11:15,786 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:11:48,228 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:12:20,426 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:12:52,693 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:13:25,030 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:13:57,251 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:14:29,581 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:15:01,726 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:15:34,091 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:16:06,721 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:16:38,925 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:17:11,156 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:17:43,525 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:18:15,822 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:18:48,129 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:19:20,326 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:19:52,526 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:20:24,758 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:20:57,076 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:21:29,386 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:22:01,676 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:22:33,827 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:23:06,134 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:23:38,424 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:24:10,687 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:24:43,076 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:25:15,256 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:25:47,489 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:26:19,800 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:26:52,275 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:27:24,688 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:27:56,923 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:28:29,183 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:29:01,484 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:29:33,691 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:30:06,053 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:30:38,482 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:31:10,683 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:31:42,858 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:32:15,029 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:32:47,323 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:33:19,458 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:33:51,784 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:34:24,275 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:34:56,429 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:35:28,821 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:36:01,175 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:36:33,578 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:37:05,857 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:37:38,184 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:38:10,579 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:38:42,822 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:39:15,025 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:39:47,430 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:40:19,655 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:40:52,076 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:41:24,230 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:41:56,482 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:42:28,752 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:43:00,925 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:43:33,155 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:44:05,451 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:44:37,753 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:45:09,954 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:45:42,156 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:46:14,376 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:46:46,583 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:47:18,850 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:47:51,187 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:48:23,427 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:48:55,728 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:49:28,035 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:50:00,221 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:50:32,689 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:51:05,175 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:51:37,376 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:52:09,827 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:52:42,076 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:53:14,225 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:53:46,581 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:54:18,757 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:54:51,187 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:55:23,452 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:55:55,625 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:56:27,953 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:57:00,185 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:57:32,424 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:58:04,853 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:58:37,122 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:59:09,557 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 17:59:41,757 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:00:14,187 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:00:46,454 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:01:18,654 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:01:50,854 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:02:23,181 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:02:55,375 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:03:27,750 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:04:00,150 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:04:32,353 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:05:04,683 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:05:37,182 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:06:09,491 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:06:41,730 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:07:14,054 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:07:46,251 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:08:18,584 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:08:50,924 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:09:23,181 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:09:55,481 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:10:27,724 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:11:00,078 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:11:32,253 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:12:04,583 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:12:36,755 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:13:09,021 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:13:41,550 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:14:13,789 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:14:46,191 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:15:18,574 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:15:50,791 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:16:23,177 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:16:55,377 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:17:27,675 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:18:00,088 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:18:32,477 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:19:04,783 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:19:37,182 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:20:09,274 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:20:41,589 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:21:14,079 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:21:46,281 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:22:18,583 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:22:51,178 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:23:23,375 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:23:55,582 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:24:27,891 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:25:00,195 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:25:32,578 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:26:04,873 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:26:37,182 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:27:09,595 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:27:41,979 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:28:14,180 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:28:46,486 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:29:18,778 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:29:51,081 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:30:23,285 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:30:55,890 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:31:28,274 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:32:00,594 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:32:32,877 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:33:05,173 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:33:37,485 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:34:09,681 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:34:42,093 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:35:14,483 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:35:46,775 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:36:19,088 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:36:51,675 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:37:23,877 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:37:56,173 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:38:28,382 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:39:00,592 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:39:33,092 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:40:05,572 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:40:37,889 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:41:10,277 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:41:42,688 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:42:14,890 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:42:47,178 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:43:19,488 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:43:51,692 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:44:23,982 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:44:56,277 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:45:28,592 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:46:00,974 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:46:33,192 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:47:05,575 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:47:37,786 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:48:10,082 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:48:42,288 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:49:14,583 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:49:46,874 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:50:19,187 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:50:51,675 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:51:23,878 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:51:56,192 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:52:28,296 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:53:00,583 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:53:33,092 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:54:05,676 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:54:37,888 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:55:10,190 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:55:42,592 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:56:14,888 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:56:47,195 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:57:19,587 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:57:51,877 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:58:24,190 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:58:56,483 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 18:59:28,782 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:00:00,979 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:00:33,180 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:01:05,573 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:01:37,779 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:02:09,982 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:02:42,193 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:03:14,592 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:03:46,984 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:04:19,279 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:04:51,594 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:05:23,977 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:05:56,179 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:06:28,486 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:07:00,694 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:07:33,193 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:08:05,583 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:08:37,794 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:09:10,182 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:09:42,487 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:10:14,776 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:10:47,194 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:11:19,494 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:11:51,791 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:12:24,089 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:12:56,487 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:13:28,781 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:14:00,980 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:14:33,275 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:15:05,583 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:15:37,779 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:16:10,072 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:16:42,388 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:17:14,675 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:17:47,176 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:18:19,486 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:18:51,875 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:19:24,082 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:19:56,279 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:20:28,582 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:21:00,890 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:21:33,182 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:22:05,483 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:22:37,686 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:23:10,074 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:23:42,487 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:24:14,877 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:24:47,285 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:25:19,693 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:25:52,182 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:26:24,578 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:26:56,793 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:27:29,187 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:28:01,481 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:28:33,684 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:29:06,287 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:29:38,592 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:30:10,993 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:30:43,281 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:31:15,488 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:31:47,888 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:32:20,181 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:32:52,377 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:33:24,686 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:33:56,983 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:34:29,283 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:35:01,580 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:35:33,792 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:36:06,279 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:36:38,478 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:37:10,781 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:37:42,987 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:38:15,376 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:38:47,577 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:39:19,785 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:39:52,082 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:40:24,490 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:40:56,780 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:41:29,077 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:42:01,281 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:42:33,580 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:43:05,789 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:43:38,185 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:44:10,583 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:44:42,875 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:45:15,175 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:45:47,487 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:46:19,784 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:46:52,178 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:47:24,482 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:47:56,780 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:48:29,076 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:49:01,285 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:49:33,687 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:50:06,288 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:50:38,575 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:51:10,888 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:51:43,277 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:52:15,579 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:52:47,877 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:53:20,187 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:53:52,585 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:54:24,977 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:54:57,275 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:55:29,482 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:56:01,692 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:56:34,089 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:57:06,680 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:57:38,984 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:58:11,381 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:58:43,589 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:59:15,975 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 19:59:48,180 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:00:20,382 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:00:52,588 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:01:24,885 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:01:57,188 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:02:29,491 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:03:01,791 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:03:34,091 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:04:06,675 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:04:38,888 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:05:11,191 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:05:43,492 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:06:15,888 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:06:48,181 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:07:20,493 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:07:52,777 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:08:24,893 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:08:57,187 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:09:29,478 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:10:01,784 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:10:34,194 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:11:06,583 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:11:38,894 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:12:11,192 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:12:43,588 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:13:15,973 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:13:48,277 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:14:20,678 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:14:52,883 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:15:25,179 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:15:57,383 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:16:29,691 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:17:02,091 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:17:34,485 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:18:06,783 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:18:39,095 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:19:11,384 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:19:43,695 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:20:16,189 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:20:48,592 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:21:21,085 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:21:53,486 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:22:25,778 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:22:58,076 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:23:30,481 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:24:02,785 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:24:35,076 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:25:07,372 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:25:39,574 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:26:11,874 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:26:44,282 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:27:16,591 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:27:48,775 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:28:21,076 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:28:53,583 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:29:25,779 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:29:57,983 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:30:30,277 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:31:02,593 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:31:35,188 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:32:07,677 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:32:39,985 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:33:12,283 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:33:44,581 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:34:16,783 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:34:49,083 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:35:21,493 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:35:53,780 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:36:26,076 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:36:58,294 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:37:30,783 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:38:03,176 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-02-01 20:38:35,587 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
