2022-01-31 08:16:00,621 WARN [hikariCP housekeeper] c.z.h.p.HikariPool [HikariPool.java:766] hikariCP - Thread starvation or clock leap detected (housekeeper delta=8h16m39s692ms916Âµs200ns).
2022-01-31 08:35:39,233 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:03:37,836 WARN [http-nio-8080-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:198] Resolved [java.lang.NullPointerException]
2022-01-31 14:08:29,187 WARN [http-nio-8080-exec-3] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:198] Resolved [java.lang.NullPointerException]
2022-01-31 14:10:04,975 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:41:24,706 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:46:21,855 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:48:12,014 WARN [restartedMain] o.m.s.m.ClassPathMapperScanner [Logger.java:44] No MyBatis mapper was found in '[com.nowcoder.community]' package. Please check your configuration.
2022-01-31 14:48:13,094 WARN [restartedMain] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [AbstractApplicationContext.java:557] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\IntelliJ IDEA 2019.3.3\projects\community\target\classes\mapper\comment-mapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'file [E:\IntelliJ IDEA 2019.3.3\projects\community\target\classes\mapper\comment-mapper.xml]'. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'Comment'.  Cause: java.lang.ClassNotFoundException: Cannot find class: Comment
2022-01-31 14:48:25,012 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:48:56,082 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:53:51,814 WARN [http-nio-8080-exec-2] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 14:59:21,492 WARN [http-nio-8080-exec-2] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 15:08:15,130 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 15:21:53,652 WARN [http-nio-8080-exec-1] c.z.h.HikariConfig [HikariConfig.java:973] hikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2022-01-31 17:24:22,520 WARN [lettuce-nioEventLoop-4-1] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@608269af.
2022-01-31 17:24:32,127 WARN [lettuce-nioEventLoop-4-2] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@7ed0852b.
2022-01-31 19:26:25,361 WARN [lettuce-nioEventLoop-4-1] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@6cc8d1a.
2022-01-31 19:26:36,102 WARN [lettuce-nioEventLoop-4-2] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@6dad29b.
2022-01-31 19:36:54,136 WARN [lettuce-nioEventLoop-4-3] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@4d08e55f.
2022-01-31 19:36:56,341 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:36:56,415 WARN [lettuce-nioEventLoop-4-4] i.n.c.n.NioEventLoop [NioEventLoop.java:850] Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@23afc14a.
2022-01-31 19:37:03,298 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:37:10,194 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:37:17,998 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:37:25,702 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:37:32,099 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:37:42,438 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:38:01,057 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:38:33,332 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:39:05,531 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:39:37,765 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:40:09,930 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:40:42,432 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:41:14,864 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:41:47,037 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:42:19,397 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:42:51,700 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:43:24,035 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:43:56,594 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:44:28,840 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:45:00,931 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:45:33,295 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:46:05,904 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:46:38,260 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:47:10,694 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:47:43,062 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:48:15,163 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:48:47,399 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:49:19,799 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:49:52,106 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:50:24,337 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:50:56,597 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:51:28,833 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:52:01,200 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:52:33,598 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:53:06,104 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:53:38,405 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:54:10,758 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:54:43,033 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:55:15,398 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:55:47,640 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:56:19,897 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:56:52,164 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:57:24,496 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:57:56,757 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:58:29,163 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:59:01,658 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 19:59:34,001 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:00:06,495 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:00:38,737 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:01:10,942 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:01:43,167 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:02:15,263 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:02:47,562 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:03:19,760 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:03:52,060 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:04:24,265 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:04:56,358 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:05:28,599 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:06:00,899 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:06:33,161 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:07:05,531 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:07:37,899 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:08:10,299 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:08:42,535 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:09:14,799 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:09:47,063 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:10:19,360 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:10:51,598 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:11:23,839 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:11:56,030 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:12:28,435 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:13:00,758 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:13:32,935 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:14:05,230 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:14:37,602 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:15:10,196 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:15:42,600 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:16:14,999 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:16:47,306 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:17:19,895 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:17:52,138 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:18:24,399 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:18:56,998 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:19:29,333 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:20:01,794 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:20:34,103 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:21:06,331 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:21:38,566 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:22:10,860 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:22:43,099 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:23:15,360 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:23:47,539 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:24:19,863 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:24:52,037 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:25:24,339 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:25:56,760 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:26:29,134 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:27:01,357 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:27:33,539 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:28:05,631 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:28:37,839 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:29:10,158 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:29:42,399 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:30:14,799 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:30:47,061 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:31:19,334 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:31:51,534 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:32:23,835 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:32:56,100 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:33:28,402 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:34:00,894 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:34:33,201 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:35:05,560 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:35:37,738 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:36:10,198 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:36:42,503 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:37:14,757 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:37:47,001 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:38:19,231 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:38:51,599 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:39:23,801 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:39:56,031 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:40:28,335 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:41:00,599 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:41:33,013 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:42:05,595 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:42:38,034 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:43:10,298 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:43:42,697 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:44:14,930 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:44:47,233 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:45:19,498 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:45:51,768 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:46:24,043 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:46:56,158 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:47:28,599 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:48:00,702 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:48:32,939 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:49:05,006 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:49:37,498 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:50:09,615 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:50:41,728 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:51:14,098 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:51:46,219 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:52:18,301 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:52:50,702 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:53:22,821 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:53:55,194 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:54:27,320 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:54:59,403 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:55:31,862 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:56:04,185 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:56:36,404 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:57:08,505 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:57:40,621 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:58:12,998 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:58:45,170 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:59:17,498 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 20:59:49,799 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:00:22,198 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:00:54,305 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:01:26,597 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:01:58,703 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:02:30,851 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:03:03,198 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:03:35,503 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:04:07,798 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:04:40,207 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:05:12,302 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:05:44,602 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:06:16,998 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:06:49,117 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:07:21,402 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:07:53,513 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:08:25,622 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:08:57,899 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:09:30,203 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:10:02,306 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:10:34,596 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:11:06,702 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:11:38,829 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:12:10,907 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:12:43,201 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:13:15,711 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:13:47,925 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:14:20,199 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:14:52,327 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:15:24,504 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:15:56,611 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:16:28,895 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:17:01,003 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:17:33,115 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:18:05,225 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:18:37,320 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:19:09,698 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:19:42,005 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:20:14,103 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:20:46,400 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:21:18,899 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:21:51,013 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:22:23,118 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:22:55,224 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:23:27,310 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:23:59,404 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:24:31,535 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:25:03,996 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:25:36,303 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:26:08,895 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:26:41,203 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:27:13,684 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:27:45,905 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:28:18,005 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:28:50,299 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:29:22,599 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:29:55,195 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:30:27,327 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:30:59,600 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:31:31,899 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:32:04,394 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:32:36,634 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:33:08,803 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:33:41,100 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:34:13,602 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:34:45,731 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:35:17,806 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:35:49,918 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:36:22,022 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:36:54,109 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:37:26,219 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:37:58,498 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:38:30,799 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:39:03,101 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:39:35,495 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:40:07,799 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:40:39,924 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:41:12,004 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:41:44,396 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:42:16,601 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:42:48,725 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:43:21,003 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:43:53,500 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:44:25,614 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:44:57,703 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:45:29,821 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:46:02,200 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:46:34,316 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:47:06,600 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:47:39,001 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:48:11,201 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:48:43,322 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:49:15,404 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:49:47,525 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:50:19,611 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:50:51,807 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:51:24,004 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:51:56,103 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:52:28,398 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:53:00,652 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:53:32,856 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:54:04,905 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:54:37,102 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:55:09,450 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:55:41,603 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:56:14,051 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:56:46,117 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:57:18,209 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:57:50,551 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:58:22,759 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:58:55,200 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:59:27,318 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 21:59:59,402 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:00:31,699 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:01:04,050 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:01:36,125 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:02:08,699 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:02:41,001 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:03:13,109 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:03:45,404 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:04:17,700 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:04:49,821 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:05:21,917 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:05:54,017 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:06:26,126 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:06:58,496 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:07:30,617 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:08:02,929 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:08:35,012 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:09:07,103 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:09:39,400 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:10:11,504 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:10:43,613 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:11:15,704 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:11:47,819 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:12:19,957 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:12:52,255 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:13:24,310 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:13:56,750 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:14:28,819 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:15:01,060 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:15:33,607 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:16:05,950 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:16:38,101 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:17:10,298 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:17:42,421 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:18:14,510 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:18:46,625 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:19:19,150 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:19:51,397 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:20:23,756 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:20:56,194 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:21:28,321 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:22:00,403 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:22:32,517 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:23:04,851 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:23:37,102 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:24:09,404 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:24:41,524 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:25:14,055 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:25:46,121 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:26:18,599 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:26:50,740 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:27:23,052 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:27:55,398 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:28:27,695 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:29:00,195 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:29:32,456 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:30:04,755 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:30:36,997 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:31:09,101 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:31:41,211 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:32:13,306 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:32:45,602 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:33:17,704 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:33:49,903 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:34:22,302 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:34:54,404 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:35:26,515 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:35:58,799 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:36:31,196 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:37:03,304 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:37:35,421 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:38:07,794 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:38:39,921 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:39:12,296 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:39:44,654 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:40:16,951 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:40:49,155 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:41:21,207 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:41:53,303 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:42:25,426 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:42:57,597 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:43:29,858 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:44:02,400 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:44:34,697 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:45:06,805 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:45:38,919 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:46:11,350 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:46:43,556 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:47:15,618 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:47:47,996 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:48:20,305 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:48:52,602 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:49:24,713 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:49:56,998 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:50:29,125 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:51:01,705 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:51:33,814 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:52:05,910 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:52:38,157 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:53:10,497 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:53:42,757 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:54:15,153 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:54:47,355 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:55:19,755 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:55:51,828 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:56:23,917 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:56:56,006 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:57:28,128 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:58:00,204 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:58:32,557 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:59:04,603 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 22:59:36,803 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:00:09,195 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:00:41,503 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:01:14,095 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:01:46,220 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:02:18,755 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:02:51,096 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:03:23,219 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:03:55,306 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:04:27,417 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:04:59,504 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:05:31,624 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:06:03,704 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:06:35,825 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:07:08,350 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:07:40,413 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:08:12,794 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:08:45,151 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:09:17,203 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:09:49,319 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:10:21,417 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:10:53,850 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:11:26,297 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:11:58,795 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:12:30,913 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:13:03,006 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:13:35,395 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:14:07,651 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:14:39,733 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:15:12,050 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:15:44,123 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:16:16,203 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:16:48,325 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:17:20,698 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:17:53,094 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:18:25,355 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:18:57,406 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:19:29,523 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:20:01,604 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:20:33,726 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:21:05,807 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:21:38,098 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:22:10,551 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:22:42,846 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:23:15,051 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:23:47,120 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:24:19,204 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:24:51,313 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:25:23,701 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:25:55,804 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:26:27,919 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:27:00,297 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:27:32,410 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:28:04,508 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:28:36,615 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:29:08,953 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:29:41,020 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:30:13,107 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:30:45,240 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:31:17,302 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:31:49,426 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:32:21,750 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:32:53,802 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:33:25,910 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:33:58,294 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:34:30,420 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:35:02,756 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:35:34,823 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:36:06,904 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:36:39,198 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:37:11,304 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:37:43,555 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:38:15,601 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:38:47,721 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:39:20,154 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:39:52,217 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:40:24,319 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:40:56,654 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:41:28,718 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:42:01,200 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:42:33,502 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:43:06,094 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:43:38,359 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:44:10,404 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:44:42,525 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:45:14,602 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:45:46,720 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:46:18,802 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:46:50,918 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:47:23,016 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:47:55,256 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:48:27,323 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:48:59,695 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:49:31,810 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:50:04,060 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:50:36,117 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:51:08,452 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:51:40,518 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:52:12,795 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:52:45,103 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:53:17,201 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:53:49,318 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:54:21,407 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:54:53,511 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:55:25,616 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:55:58,095 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:56:30,397 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:57:02,895 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:57:35,023 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:58:07,108 WARN [lettuce-nioEventLoop-4-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:58:39,298 WARN [lettuce-nioEventLoop-4-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:59:11,408 WARN [lettuce-nioEventLoop-4-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
2022-01-31 23:59:43,696 WARN [lettuce-nioEventLoop-4-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:176] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
